# Generated by Django 3.1.2 on 2021-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illust', '0002_auto_20210515_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='file',
            field=models.FileField(upload_to='illust/file/', verbose_name='ファイル'),
        ),
        migrations.AlterField(
            model_name='design',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='illust/thumbnail/', verbose_name='サムネイル'),
        ),
    ]
